# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.


# Site settings
title: 马达数据官方博客
email: hi@madadata.com
description: > # this means to ignore newlines until "baseurl:"
  Data is insight.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://Madadata.github.io" # the base hostname & protocol for your site
github_username: Madadata

# Build settings
markdown: kramdown
paginate: 4
author: 马达数据
gems: [jekyll-paginate]
